### ISSUE TITLE
Image is very blue-ish

### ISSUE THREAD

**Issue by xseignard** [orgicus/ofxCvPiCam#11]
Hello,

Thanks for your lib, it works pretty OK. But I have a weird problem, the image is very blue where it should be red and red where it should be blue! As if channels R and B are inverted?!

Here is a pic describing the problem:
![img_20170626_124212_1](https://user-images.githubusercontent.com/515603/27535942-1fbf6ede-5a6d-11e7-92d0-8d52b7c651b0.jpg)

I don't face the problem usin `raspivid` with the same hardware.

Any idea?

**Comment by orgicus** [comment]
Hi,

Thank you  for the helpful debug image. That is weird indeed.
What version of the PiCamera module are you using ? (is the original one or the newer PiCam2) ?

Unfortunately I haven't managed the time to revisit the add-on and test with newer versions of Raspberry Pi and Pi Cameras.

Would you willing to test a hacky fix attempt ?
At lines [68](https://github.com/orgicus/ofxCvPiCam/blob/master/src/ofxCvPiCam.cpp#L68) and [69](https://github.com/orgicus/ofxCvPiCam/blob/master/src/ofxCvPiCam.cpp#L69) would you be able to swap `MMAL_ENCODING_BGR24` for `MMAL_ENCODING_RGB24` ?

Thank you,
George

**Comment by xseignard** [comment]
Hello @orgicus !
Your workaround worked, thanks!
Here is the camera I use: http://www.arducam.com/spy-camera-raspberry-pi/

Don't know what that would mean compared to the orginal RPi camera module, but hey, the workaround works!

Thanks
Regards

Xavier

**Comment by orgicus** [comment]
Good to hear that worked! :)

I didn't know about the Spy Camera for Raspberry Pi: looks slick.
Specs look the same to the [Camera Module v1](https://www.raspberrypi.org/documentation/hardware/camera/).

Thanks for testing and providing the details. Hopefully this will be helpful for others using the same module in the future.

Best of luck with your project !
